# Generated by Django 4.0 on 2021-12-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddess',
            new_name='ShippingAddress',
        ),
    ]
