# Generated by Django 4.0 on 2021-12-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='address',
        ),
    ]
