# Generated by Django 4.0 on 2022-01-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_shippingaddress_user_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
